CREATE TABLE coupon (
    id BINARY(16) PRIMARY KEY DEFAULT (UUID_TO_BIN(UUID())),
    code VARCHAR(100) NOT NULL,
    discount INTEGER NOT NULL,
    valid TIMESTAMP NOT NULL,
    event_id BINARY(16),
    FOREIGN KEY (event_id) REFERENCES event(id) ON DELETE CASCADE
);
